import "./globals.css";
import { Inter, Dancing_Script, Caveat } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const dancing_script = Dancing_Script({ subsets: ["latin"] });
const caveat_font = Caveat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}